options:
  app_path:
    type: string
    default: "/srv/app"
    description: "Where Dokuwiki will be installed"
  admin_user:
    type: string
    default: admin
    description: "Admin username (default: admin)"
  admin_password:
    type: string
    default: $6$nzJoWjF10$ocTL4Zxbh7P6vQXhBz223NqviL9DdnUzDiYtnTv9sLHgzkemuC0q4sBZ4on2F7C/X3ALJHONmdMunAJqa3TVo0
    description: "Admin password sha512 hash format (default password: password)"
  admin_name:
    type: string
    default: "The Admin"
    description: Admin name
  admin_email:
    type: string
    default: "admin@example.com"
    description: Admin email
