options:
  app_path:
    type: string
    default: "/srv/app"
    description: "Where Dokuwiki will be installed"
  admin_user:
    type: string
    default: ""
    description: "Admin username"
  admin_password:
    type: string
    default: ""
    description: "Admin password sha512 hash format (see README for using mkpasswd to generate one.)"
  admin_name:
    type: string
    default: "The Admin"
    description: Admin name
  admin_email:
    type: string
    default: "admin@example.com"
    description: Admin email
