#!/usr/bin/env ruby
require_relative '../bundle/bundler/setup'
require 'charmkit'

package [
    'nginx-full', 'php-fpm',      'php-cgi',      'php-curl', 'php-gd', 'php-json',
    'php-mcrypt', 'php-readline', 'php-mbstring', 'php-xml'
  ], :update_cache

hook_path = ENV['JUJU_CHARM_DIR']
app_path = config 'app_path'

mkdir app_path unless is_dir? app_path

release = config 'release'
begin
  resource_path = resource "#{release}-release"
rescue
  status :blocked, "Unknown release given #{release}"
  exit 1
end

run "tar xf #{resource_path} -C #{app_path} --strip-components=1"

rm "#{app_path}/conf/install.php" unless !is_file? "#{app_path}/conf/install.php"
