#!/usr/bin/env ruby
require_relative '../bundle/bundler/setup'
require 'charmkit'

package [
    'nginx-full', 'php-fpm',      'php-cgi',      'php-curl', 'php-gd', 'php-json',
    'php-mcrypt', 'php-readline', 'php-mbstring', 'php-xml'
  ], :update_cache

app_path = config 'app_path'

mkdir app_path unless is_dir? app_path

run "wget -q -O /tmp/dokuwiki.tgz http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz"
run "tar xf /tmp/dokuwiki.tgz -C #{app_path} --strip-components=1"
run "rm -rf #{app_path}/conf/install.php" unless is_file? "#{app_path}/conf/install.php"
