#!/bin/sh

if ! dpkg -s ruby; then
    apt-get update && apt-get install -qyf ruby --no-install-recommends
fi

gem install bundler && bundle install --local --quiet

# Do install task
bundle exec rake dokuwiki:install
